export const TIERS = ['Stone Age', 'Steam', 'LV', 'MV', 'HV']

export const MACHINES = [
  'Forge Hammer',
  'Steam Macerator',
  'Compressor',
  'Wiremill',
  'Lathe',
  'Bending Machine',
  'Assembler',
  'Alloy Smelter',
  'Extractor',
  'Macerator',
]

export const tierRank = Object.fromEntries(TIERS.map((tier, index) => [tier, index]))

export const rawItems = {
  iron_ingot: 'Iron Ingot',
  copper_ingot: 'Copper Ingot',
  tin_ingot: 'Tin Ingot',
  wrought_iron_ingot: 'Wrought Iron Ingot',
  red_alloy_ingot: 'Red Alloy Ingot',
  glass: 'Glass',
}

export const items = [
  {
    id: 'steel_ingot',
    name: 'Steel Ingot',
    category: '재료',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'Steam',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Steam 기계, LV 기반 시설, 기계 부품, EBF 준비까지 계속 소모되는 초반 핵심 진행 재료입니다.',
    uses: ['Steam 기계', 'Machine Hull 계열', 'Plate / Rod / Screw', 'EBF 준비'],
    stock: 'Steam 단계에서는 가능하면 여러 스택을 확보하고, LV 이후에는 Plate와 Rod 제작을 편하게 만드는 것이 좋습니다.',
    warning: 'EBF와 MV 준비 직전에 Steel 수요가 급격히 늘어납니다.',
    tags: ['핵심', '재료', '자주사용', 'core', 'material', 'frequent'],
  },
  {
    id: 'rubber',
    name: 'Rubber',
    category: '재료',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'Steam',
    automationFromTier: 'LV',
    importance: 5,
    summary: '초반 케이블, 회로, 전기 부품에 계속 들어가는 기본 재료입니다.',
    uses: ['Tin Cable', 'Copper Cable', 'Circuit 계열', '전기 부품'],
    stock: 'Steam/LV에서는 최소 1~2스택 정도를 유지하고, 반복 제작이 귀찮아지는 시점부터 추출 공정을 자동화하는 것을 추천합니다.',
    warning: 'Rubber가 떨어지면 초반 전기 제작 라인이 거의 전부 막히기 쉽습니다.',
    tags: ['핵심', '재료', '자주사용', 'core', 'material', 'frequent'],
  },
  {
    id: 'copper_wire',
    name: 'Copper Wire',
    category: '전선',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Motor, Circuit, Coil, 초반 기계 부품에 자주 들어가는 대표적인 전선 재료입니다.',
    uses: ['LV Electric Motor', 'Basic Circuit', 'Coil 계열', 'Cable 제작'],
    stock: 'LV에서는 Wiremill 경로를 우선 사용하고, 항상 약간의 여분을 유지하는 것이 좋습니다.',
    warning: '수동 전선 제작은 보통 Wiremill보다 재료 효율이 낮습니다.',
    tags: ['전선', '핵심', '자주사용', 'wire', 'core', 'frequent'],
  },
  {
    id: 'tin_wire',
    name: 'Tin Wire',
    category: '전선',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 4,
    summary: 'Tin Cable과 LV 부품 제작에 주로 쓰이는 초반 전선입니다.',
    uses: ['Tin Cable', 'LV 전력 배선', 'LV Electric Motor'],
    stock: 'LV에서 기계를 여러 개 늘릴 계획이면 묶음 단위로 만들어두면 편합니다.',
    warning: '반복 생산이 시작되면 Wiremill 경로를 쓰는 것이 좋습니다.',
    tags: ['전선', '자주사용', 'wire', 'frequent'],
  },
  {
    id: 'tin_cable',
    name: 'Tin Cable',
    category: '케이블',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'LV 초반 표준 케이블이며, LV 부품과 기계 제작에도 자주 들어갑니다.',
    uses: ['LV Electric Motor', 'LV 기계', 'LV 전력 배선'],
    stock: 'LV에서 기계를 여러 개 만들 계획이면 32~64개 정도를 확보해두면 편합니다.',
    warning: '기계를 한 번에 여러 개 만들 때 Cable 수요가 갑자기 증가합니다.',
    tags: ['케이블', '핵심', '자주사용', '계산기', 'cable', 'core', 'frequent', 'calculator'],
  },
  {
    id: 'iron_rod',
    name: 'Iron Rod',
    category: '부품',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'Steam',
    automationFromTier: 'LV',
    importance: 4,
    summary: 'Motor, Piston, 도구, 초반 기계 레시피에 자주 들어가는 기본 부품입니다.',
    uses: ['LV Electric Motor', 'Piston 계열', '도구', '기계 부품'],
    stock: 'Steam/LV에서 소량 버퍼를 유지하면 편합니다. Lathe가 있으면 Lathe 경로를 우선 추천합니다.',
    warning: '초반에는 수동 제작도 가능하지만, 반복되면 금방 귀찮아집니다.',
    tags: ['부품', '자주사용', 'component', 'frequent'],
  },
  {
    id: 'magnetic_iron_rod',
    name: 'Magnetic Iron Rod',
    category: '부품',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 4,
    summary: 'LV Motor와 여러 전기 부품에 들어가는 하위 부품입니다.',
    uses: ['LV Electric Motor', '전기 부품'],
    stock: 'LV에서는 Motor를 만들 때 함께 묶음 단위로 제작하는 것이 좋습니다.',
    warning: '현재 레시피는 팩 버전별 검증 전 placeholder로 표시되어 있습니다.',
    tags: ['부품', '자주사용', '계산기', 'component', 'frequent', 'calculator'],
  },
  {
    id: 'lv_electric_motor',
    name: 'LV Electric Motor',
    category: '부품',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Pump, Conveyor, Piston, Robot Arm, 각종 LV 기계에 들어가는 LV 핵심 부품입니다.',
    uses: ['LV Electric Pump', 'LV Conveyor Module', 'LV Electric Piston', 'LV 기계'],
    stock: 'LV 초반에는 4~8개, LV 후반/MV 준비 전에는 16개 이상 또는 반자동화를 추천합니다.',
    warning: 'Assembler와 Wiremill이 있으면 제작 체감 난이도가 크게 내려갑니다.',
    tags: ['부품', '핵심', '자주사용', '계산기', 'component', 'core', 'frequent', 'calculator'],
  },
  {
    id: 'basic_circuit',
    name: 'Basic Circuit',
    category: '회로',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: '초반 첫 번째 주요 회로 병목입니다. 많은 LV 기계와 부품에 필요합니다.',
    uses: ['LV 기계', 'Electronic Circuit', '기계 부품'],
    stock: 'LV에서는 재료가 허락하는 선에서 8~16개 단위로 묶어서 만들면 편합니다.',
    warning: '회로 레시피는 팩 버전과 진행도에 따라 달라질 수 있습니다. 현재 항목은 UI 테스트용 간이 레시피입니다.',
    tags: ['회로', '핵심', '자주사용', '계산기', 'circuit', 'core', 'frequent', 'calculator'],
  },
  {
    id: 'lv_machine_hull',
    name: 'LV Machine Hull',
    category: '기계 부품',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: '대부분의 LV 기계 몸체가 되는 부품입니다. 기지를 확장할수록 반복 병목이 됩니다.',
    uses: ['LV 기계', 'Generator', '기계 업그레이드'],
    stock: 'LV에서 기계를 여러 개 만들기 전에는 몇 개를 미리 준비해두는 것이 좋습니다.',
    warning: '중간에 제작 흐름이 끊기지 않도록 Plate와 Cable을 먼저 준비하는 것이 좋습니다.',
    tags: ['기계', '핵심', '자주사용', 'machine', 'core', 'frequent'],
  },
  {
    id: 'lv_assembler',
    name: 'LV Assembler',
    category: '기계',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: '반복 부품 제작을 크게 편하게 만들어주는 고우선순위 LV 기계입니다.',
    uses: ['Motor', 'Cable', 'Circuit', '기계 부품'],
    stock: 'LV 초반에 1대는 빨리 만드는 것을 추천합니다.',
    warning: 'Assembler가 생기면 여러 레시피가 훨씬 관리하기 쉬워집니다.',
    tags: ['기계', '핵심', '추천', 'machine', 'core', 'recommended'],
  },
  {
    id: 'cupronickel_coil',
    name: 'Cupronickel Coil',
    category: 'EBF 부품',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'MV',
    importance: 4,
    summary: 'Electric Blast Furnace 준비에 쓰이는 초반 Coil 재료입니다.',
    uses: ['Electric Blast Furnace', 'Heating Coil'],
    stock: 'LV에서 EBF를 준비할 때 필요한 만큼 계획적으로 제작합니다.',
    warning: '정확한 EBF 구성 계획을 확인하기 전에는 과잉 생산하지 않는 것이 좋습니다.',
    tags: ['EBF', '진행', 'ebf', 'progression'],
  },
]

export const recipes = [
  {
    id: 'iron_rod_lathe',
    output: { itemId: 'iron_rod', amount: 2 },
    inputs: [{ itemId: 'iron_ingot', amount: 1 }],
    machine: 'Lathe',
    tier: 'LV',
    note: 'Lathe 확보 후 추천 경로입니다.',
    tags: ['recommended'],
  },
  {
    id: 'copper_wire_wiremill',
    output: { itemId: 'copper_wire', amount: 2 },
    inputs: [{ itemId: 'copper_ingot', amount: 1 }],
    machine: 'Wiremill',
    tier: 'LV',
    note: 'Wiremill 확보 후 추천 경로입니다.',
    tags: ['recommended'],
  },
  {
    id: 'tin_wire_wiremill',
    output: { itemId: 'tin_wire', amount: 2 },
    inputs: [{ itemId: 'tin_ingot', amount: 1 }],
    machine: 'Wiremill',
    tier: 'LV',
    note: 'Wiremill 확보 후 추천 경로입니다.',
    tags: ['recommended'],
  },
  {
    id: 'tin_cable_assembler',
    output: { itemId: 'tin_cable', amount: 1 },
    inputs: [
      { itemId: 'tin_wire', amount: 1 },
      { itemId: 'rubber', amount: 1 },
    ],
    machine: 'Assembler',
    tier: 'LV',
    note: '프로토타입용 간이 경로입니다.',
    tags: ['recommended'],
  },
  {
    id: 'magnetic_iron_rod_placeholder',
    output: { itemId: 'magnetic_iron_rod', amount: 1 },
    inputs: [{ itemId: 'iron_rod', amount: 1 }],
    machine: 'Manual / Polarizer placeholder',
    tier: 'LV',
    note: '정확한 GTNH 레시피 검증 전 placeholder입니다.',
    tags: ['placeholder'],
  },
  {
    id: 'lv_electric_motor_assembler',
    output: { itemId: 'lv_electric_motor', amount: 1 },
    inputs: [
      { itemId: 'magnetic_iron_rod', amount: 1 },
      { itemId: 'copper_wire', amount: 2 },
      { itemId: 'tin_cable', amount: 2 },
      { itemId: 'iron_rod', amount: 2 },
    ],
    machine: 'Assembler',
    tier: 'LV',
    note: '프로토타입용 경로입니다. 실제 수량은 GTNH 팩 버전 기준으로 검증해야 합니다.',
    tags: ['recommended', 'placeholder'],
  },
  {
    id: 'basic_circuit_placeholder',
    output: { itemId: 'basic_circuit', amount: 1 },
    inputs: [
      { itemId: 'copper_wire', amount: 4 },
      { itemId: 'rubber', amount: 2 },
      { itemId: 'steel_ingot', amount: 1 },
    ],
    machine: 'Assembler',
    tier: 'LV',
    note: 'UI 테스트용 placeholder 회로 레시피입니다.',
    tags: ['placeholder'],
  },
]
