export const TIERS = ['Stone Age', 'Steam', 'LV', 'MV', 'HV']

export const MACHINES = [
  'Forge Hammer',
  'Steam Macerator',
  'Compressor',
  'Wiremill',
  'Lathe',
  'Bending Machine',
  'Assembler',
  'Alloy Smelter',
  'Extractor',
  'Macerator',
]

export const tierRank = Object.fromEntries(TIERS.map((tier, index) => [tier, index]))

export const rawItems = {
  iron_ingot: 'Iron Ingot',
  copper_ingot: 'Copper Ingot',
  tin_ingot: 'Tin Ingot',
  wrought_iron_ingot: 'Wrought Iron Ingot',
  red_alloy_ingot: 'Red Alloy Ingot',
  glass: 'Glass',
}

export const items = [
  {
    id: 'steel_ingot',
    name: 'Steel Ingot',
    category: 'Material',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'Steam',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Core progression material for Steam machines, LV infrastructure, machine parts, and EBF preparation.',
    uses: ['Steam machines', 'Machine hulls', 'Plates / rods / screws', 'EBF preparation'],
    stock: 'Steam: several stacks if possible. LV: keep plate and rod production convenient.',
    warning: 'Steel demand rises quickly before EBF and MV preparation.',
    tags: ['core', 'material', 'frequent'],
  },
  {
    id: 'rubber',
    name: 'Rubber',
    category: 'Material',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'Steam',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Constantly consumed by early cables, circuits, and electric components.',
    uses: ['Tin Cable', 'Copper Cable', 'Circuits', 'Machine components'],
    stock: 'Steam/LV: keep at least 1–2 stacks. Automate extraction once it becomes annoying.',
    warning: 'Running out of rubber blocks many early electric crafting chains.',
    tags: ['core', 'material', 'frequent'],
  },
  {
    id: 'copper_wire',
    name: 'Copper Wire',
    category: 'Wire',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'A frequent wire component used in motors, circuits, coils, and early machine parts.',
    uses: ['LV Electric Motor', 'Basic Circuit', 'Coils', 'Cables'],
    stock: 'LV: use Wiremill whenever possible and keep a small buffer.',
    warning: 'Manual wire crafting is usually less efficient than Wiremill processing.',
    tags: ['wire', 'core', 'frequent'],
  },
  {
    id: 'tin_wire',
    name: 'Tin Wire',
    category: 'Wire',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 4,
    summary: 'Early wire used mainly for tin cables and LV component chains.',
    uses: ['Tin Cable', 'LV power routing', 'LV Electric Motor'],
    stock: 'LV: make in batches when expanding machines.',
    warning: 'Wiremill route is preferred for repeated production.',
    tags: ['wire', 'frequent'],
  },
  {
    id: 'tin_cable',
    name: 'Tin Cable',
    category: 'Cable',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Standard early cable and a common ingredient in LV components and machines.',
    uses: ['LV Electric Motor', 'LV machines', 'LV power routing'],
    stock: 'LV: keep 32–64 if building several machines.',
    warning: 'Cable demand spikes when you batch-craft machines.',
    tags: ['cable', 'core', 'frequent', 'calculator'],
  },
  {
    id: 'iron_rod',
    name: 'Iron Rod',
    category: 'Component',
    craftableFromTier: 'Steam',
    recommendedFromTier: 'Steam',
    automationFromTier: 'LV',
    importance: 4,
    summary: 'Basic component used by motors, pistons, tools, and early machine recipes.',
    uses: ['LV Electric Motor', 'Pistons', 'Tools', 'Machine components'],
    stock: 'Steam/LV: keep a small buffer. Lathe route is preferred when available.',
    warning: 'Manual crafting is okay early, but becomes repetitive later.',
    tags: ['component', 'frequent'],
  },
  {
    id: 'magnetic_iron_rod',
    name: 'Magnetic Iron Rod',
    category: 'Component',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 4,
    summary: 'Required subcomponent for LV motors and other electric parts.',
    uses: ['LV Electric Motor', 'Electric components'],
    stock: 'LV: make in batches together with motor production.',
    warning: 'This recipe is marked as placeholder until verified against your pack version.',
    tags: ['component', 'frequent', 'calculator'],
  },
  {
    id: 'lv_electric_motor',
    name: 'LV Electric Motor',
    category: 'Component',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Core LV component used in pumps, conveyors, pistons, robot arms, and many machines.',
    uses: ['LV Electric Pump', 'LV Conveyor Module', 'LV Electric Piston', 'LV machines'],
    stock: 'LV early: 4–8. LV late/MV prep: 16+ or semi-automated.',
    warning: 'Assembler + Wiremill makes the chain much less painful.',
    tags: ['component', 'core', 'frequent', 'calculator'],
  },
  {
    id: 'basic_circuit',
    name: 'Basic Circuit',
    category: 'Circuit',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'One of the first major circuit bottlenecks. Needed for many LV machines and components.',
    uses: ['LV machines', 'Electronic Circuit', 'Machine components'],
    stock: 'LV: batch 8–16 when materials allow.',
    warning: 'Circuit recipes vary. Current recipe is a clean prototype placeholder.',
    tags: ['circuit', 'core', 'frequent', 'calculator'],
  },
  {
    id: 'lv_machine_hull',
    name: 'LV Machine Hull',
    category: 'Machine Part',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'Body of most LV machines. A repeated bottleneck when expanding your base.',
    uses: ['LV machines', 'Generators', 'Machine upgrades'],
    stock: 'LV: prepare several before a machine-crafting session.',
    warning: 'Prepare plates and cables first to avoid recipe interruptions.',
    tags: ['machine', 'core', 'frequent'],
  },
  {
    id: 'lv_assembler',
    name: 'LV Assembler',
    category: 'Machine',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'LV',
    importance: 5,
    summary: 'High-priority LV machine that simplifies repeated component crafting.',
    uses: ['Motors', 'Cables', 'Circuits', 'Machine components'],
    stock: 'LV: one early assembler is strongly recommended.',
    warning: 'Many recipes become easier once this is available.',
    tags: ['machine', 'core', 'recommended'],
  },
  {
    id: 'cupronickel_coil',
    name: 'Cupronickel Coil',
    category: 'EBF Part',
    craftableFromTier: 'LV',
    recommendedFromTier: 'LV',
    automationFromTier: 'MV',
    importance: 4,
    summary: 'Early coil material for Electric Blast Furnace preparation.',
    uses: ['Electric Blast Furnace', 'Heating coils'],
    stock: 'LV: prepare when planning your EBF.',
    warning: 'Do not overproduce before checking your exact EBF plan.',
    tags: ['ebf', 'progression'],
  },
]

export const recipes = [
  {
    id: 'iron_rod_lathe',
    output: { itemId: 'iron_rod', amount: 2 },
    inputs: [{ itemId: 'iron_ingot', amount: 1 }],
    machine: 'Lathe',
    tier: 'LV',
    note: 'Preferred route after Lathe.',
    tags: ['recommended'],
  },
  {
    id: 'copper_wire_wiremill',
    output: { itemId: 'copper_wire', amount: 2 },
    inputs: [{ itemId: 'copper_ingot', amount: 1 }],
    machine: 'Wiremill',
    tier: 'LV',
    note: 'Preferred route after Wiremill.',
    tags: ['recommended'],
  },
  {
    id: 'tin_wire_wiremill',
    output: { itemId: 'tin_wire', amount: 2 },
    inputs: [{ itemId: 'tin_ingot', amount: 1 }],
    machine: 'Wiremill',
    tier: 'LV',
    note: 'Preferred route after Wiremill.',
    tags: ['recommended'],
  },
  {
    id: 'tin_cable_assembler',
    output: { itemId: 'tin_cable', amount: 1 },
    inputs: [
      { itemId: 'tin_wire', amount: 1 },
      { itemId: 'rubber', amount: 1 },
    ],
    machine: 'Assembler',
    tier: 'LV',
    note: 'Prototype route.',
    tags: ['recommended'],
  },
  {
    id: 'magnetic_iron_rod_placeholder',
    output: { itemId: 'magnetic_iron_rod', amount: 1 },
    inputs: [{ itemId: 'iron_rod', amount: 1 }],
    machine: 'Manual / Polarizer placeholder',
    tier: 'LV',
    note: 'Placeholder until verified.',
    tags: ['placeholder'],
  },
  {
    id: 'lv_electric_motor_assembler',
    output: { itemId: 'lv_electric_motor', amount: 1 },
    inputs: [
      { itemId: 'magnetic_iron_rod', amount: 1 },
      { itemId: 'copper_wire', amount: 2 },
      { itemId: 'tin_cable', amount: 2 },
      { itemId: 'iron_rod', amount: 2 },
    ],
    machine: 'Assembler',
    tier: 'LV',
    note: 'Prototype route; verify exact GTNH recipe before using as authoritative.',
    tags: ['recommended', 'placeholder'],
  },
  {
    id: 'basic_circuit_placeholder',
    output: { itemId: 'basic_circuit', amount: 1 },
    inputs: [
      { itemId: 'copper_wire', amount: 4 },
      { itemId: 'rubber', amount: 2 },
      { itemId: 'steel_ingot', amount: 1 },
    ],
    machine: 'Assembler',
    tier: 'LV',
    note: 'Placeholder circuit recipe for UI testing.',
    tags: ['placeholder'],
  },
]
